<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link rel="stylesheet" href="/public/css/body.css">
	<title>Teambits</title>
</head>
<body>
	<!-- #LOGO -->
	<img src="/public/img/logo_teambits.png" class="logo">
	<!-- #NAVBAR -->
	<link rel="stylesheet" href="/public/css/navbar.css">
	<script src="/public/js/navbar.js"></script>
	<div class="sidenav">
		<div class="sidenavSubTitle">
			<h3>Teambits</h3>
			<h3 onclick="closeSidenav()">X</h3>
		</div>
		<div class="menus">
			<div class="meetus">
				<div class="sidenavTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
					<li><a href="/projects">Casos de éxito</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="sidenavTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="sidenavTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
			</div>

			<div class="projects">
				<div class="sidenavTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="navbar">
		<!-- <div class="title">
			
			Teambits
		</div> -->
		<span class="burgerMenu" onclick="openSidenav()">Menu</span>

		<div class="links">
			<a class="link" href="/"><p>Inicio</p></a>
			<a class="link" href="/about"><p>Acerca de nosotros</p></a>
			<a class="link" href="/services"><p>Servicios</p></a>
			<a class="link" href="/products"><p>Productos</p></a>
			<a class="link" href="/projects"><p>Proyectos</p></a>
			<a class="link" href="/board"><p>Bolsa de trabajo</p></a>
		</div>
	</div>
	<!-- TEMPLATES -->
	<link rel="stylesheet" href="/public/css/about.css">
	<div class="about section">
		<div class="aboutTitle">Acerca de Teambits</div>
		<div class="aboutContent">
			<div class="content" id="about">
			<p>Teambits, S.C. es una empresa 100% Mexicana, formada a principios del año 2009, dedicada a la consultoría, capacitación y
				desarrollo de proyectos en sistemas de información, brindando siempre una actitud de profesionalismo en sus servicios y
				soluciones. 
				<br><br>
				En nuestra creación unimos tres conceptos básicos que engloban las necesidades de cualquier empresa en el área
				de sistemas, los cuales son: información, tecnología y solución. 
				<br><br>
				En los últimos años el desarrollo de la tecnología ha
				permitido a las empresas a tener acceso a un gran número de herramientas, metodologías y técnicas para obtener el mayor número
				de beneficios a su negocio, pero al mismo tiempo el desarrollo de la tecnología ha vuelto las cosas más complicadas y especializadas
				y dentro de este mundo de opciones lo que realmente necesitan las empresas de hoy son soluciones óptimas para la utilización
				apropiada de la tecnología de información, cómputo y comunicaciones para el éxito de su negocio.</p>

			<h2>Diferencia de la competencia</h2>
			<ul>
				<li>Actitud en el servicio</li>
				<li>Disponibilidad</li>
				<li>Contacto y atención</li>
				<li>Asesoría al cliente acorde a su negocio</li>
				<li>Compromiso</li>
				<li>Satisfacción</li>
				<li>Oportunidad</li>
				<li>Iniciativa</li>
			</ul>
		</div>
		<div class="content" id="image">
			<img src="https://s-media-cache-ak0.pinimg.com/736x/15/37/c2/1537c2445e0c414f3a4e9c2478bfcc40--m%C3%A9xico-city-world-trade-center.jpg" alt="">
		</div>
		</div>
	</div>

	<div class="values section" id="valuesSection">
		<div class="title" align="center">Nuestros Valores</div>
		<div class="content" id="values">
			<div>
				<b>Confiabilidad: </b>
				Somos eficaces y eficientes en la ejecución de nuestras actividades 
				<br><br>
				<b>Equipo Teambits: </b>
				Somos un equipo de consultores
				orgullosamente Teambits 
				<br><br>
				<b>Liderazgo estratégico: </b>
				Liderazgo que convierte la estrategia en realidad
			</div>
			<div align="center"><img src="http://www.representacionesdinamicasinternacionales.com.mx/images/valores.png" alt=""></div>
			<div>
				<b>Servicio Teambits: </b>
				Un cliente satisfecho es la meta a lograr 
				<br><br>
				<b>Proactividad: </b>
				El dinamismo nos distingue 
				<br><br>
				<b>Enfoque a la gente:</b>
				Ninguno de nosotros es tan bueno como todos juntos
			</div>
		</div>
	</div>

	<div class="alliance section" id="alliances">
		<div class="title" align="center">Alianzas</div>
		<div class="alliancesFormat">
			<div class="allianceImage" align="center">
				<img src="/public/img/controlbi.png">
			</div>
			<div class="allianceText">
				<h4>CONTROL BI – COSTA RICA</h4>
				<p>
					En 2016, se firmó contrato con Control BI, empresa Costarricense, especializada en SOFOMES,
					SOFIPOS y SOFOLES (casas de ahorro) para en conjunto utilizar el Core bancario y contabilidad para adecuarlo con la facturación
					electrónica. Esta alianza le representa a Teambits el ofrecer soluciones en el sector bancario con el crecimiento a servicios
					usando la telefonía celular y dispositivos móviles, con clientes en México, Centroamérica y Suramérica.
				</p>
			</div>
		</div>

		<div class="alliancesFormat">
			<div class="allianceImage" align="center">
				<img src="/public/img/microsoft.png">
			</div>
			<div class="allianceText">
				<h4>MICROSOFT</h4>
				<p>
					En 2017, Teambits S.C. firmó contrato con Microsoft México para promover servicios en la nube
					a través de Azure de Microsoft.
				</p>
			</div>
		</div>

		<div class="alliancesFormat">
			<div class="allianceImage" align="center">
				<img src="/public/img/nephtos.png">
			</div>
			<div class="allianceText">
				<h4>NephosIT</h4>
				<p>
					Nuestra alianza con Nephos-IT nos permite ofrecer a nuestros clientes opciones competitivas en soluciones de HW en la nube
					así como venta de equipo hiperconvergente. <br> En conjunto hemos logrado mantener el nivel esperado de satisfacción
					del cliente, sistemas estables, disponibilidad 7x24.
				</p>
			</div>				
		</div>
		
	</div>

	<div class="mission section" id="mission">
		<div class="title" align="center">Misión</div>
		<br>
		<div class="" align="center">
			<p>Soluciones de software para desarrollar tus ideas.</p>
			<p>Consultores Teambits altamente capacitados en tecnología, metodología y conocimiento de negocio.</p>
			<p>Lograr que nuestros consultores estén orgullosos y satisfechos de pertenecer a la familia Teambits.</p>
			<p>Generando beneficios a nuestros clientes, consultores, sociedad y país.</p>
		</div>
	</div>
	<div class="vision section">
		<div class="title" align="center">Visión</div>
		<br>
		<div class="" align="center">
			<p>Ser líderes en el desarrollo de soluciones y productos innovadores de Tecnologías de la información a nivel Nacional y
				global.
			</p>
			<p>Ser uno de los mejores lugares para trabajar.</p>
		</div>
	</div>

	<div class="objectives section" id="objectives">
		<div class="title" align="center">Objetivos</div>
		<div class="content">
			<div>
				<p>
					Proporcionar a nuestros clientes soluciones en proyectos con infraestructura tecnológica abierta y adaptable, involucrando
					la reingeniería, consultoría especializada, soporte técnico, desarrollo y capacitación de manera integral y referenciada,
					considerando la implementación en tecnologías homogéneas y heterogéneas.
				</p>
				<p>
					Ofrecer servicios con valor agregado, proporcionando soluciones personalizadas y cumpliendo los requerimientos específicos
					de cada proyecto.
				</p>
			</div>
			<div>
				<p>
					Mantenernos a la vanguardia tecnológica e implementación de soluciones empresariales completas asegurando las mejores condiciones
					costo/beneficio con soluciones innovadoras que aseguren el retorno de la inversión realizada.
				</p>
				<p>
					Identificar y proponer áreas de oportunidad para garantizar la disponibilidad, confiabilidad y seguridad de la información.
				</p>
			</div>
			<div>
				<p>
					Proporcionar servicios de Expertise Training, que sirvan para disminuir la curva de aprendizaje de los DBA's encargados del
					mantenimiento de las bases de datos aprovechando el expertise de los DBA's de Teambits.
				</p>
				<p>
					Brindar un servicio de soporte para emergencias (7x24), con una respuesta inmediata.
				</p>
			</div>
		</div>
	</div>
	</div>
	<!-- FOOTER -->
	<link rel="stylesheet" href="/public/css/footer.css">
	<div class="footer">
		<div class="menus">
			<div class="contact">
				<div class="contactLogo">
					<img src="/public/img/footLogo.png">
				</div>
			</div>

			<div class="meetus">
				<div class="footerTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="footerTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="footerTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products/dpl">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
			</div>

			<div class="projects">
				<div class="footerTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>
		</div>
	</div>
</body>
</html>