<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="/public/css/body.css">
    <link rel="stylesheet" href="/public/css/b4c.css">
	<title>Teambits</title>
</head>
<body>
	<!-- #LOGO -->
	<img src="/public/img/logo_teambits.png" class="logo">
	<!-- #NAVBAR -->
	<link rel="stylesheet" href="/public/css/navbar.css">
	<script src="/public/js/navbar.js"></script>
	<div class="sidenav">
		<div class="sidenavSubTitle">
			<h3>Teambits</h3>
			<h3 onclick="closeSidenav()">X</h3>
		</div>
		<div class="menus">
			<div class="meetus">
				<div class="sidenavTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="sidenavTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="sidenavTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
			</div>

			<div class="projects">
				<div class="sidenavTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="navbar">
		<!-- <div class="title">
			
			Teambits
		</div> -->
		<span class="burgerMenu" onclick="openSidenav()">Menu</span>

		<div class="links">
			<a class="link" href="/"><p>Inicio</p></a>
			<a class="link" href="/about"><p>Acerca de nosotros</p></a>
			<a class="link" href="/services"><p>Servicios</p></a>
			<a class="link" href="/products"><p>Productos</p></a>
			<a class="link" href="/projects"><p>Proyectos</p></a>
			<a class="link" href="/board"><p>Bolsa de trabajo</p></a>
		</div>
	</div>
	<!-- TEMPLATES -->
	<div id="b4c">
        <div class="subtitle">Programa B4C</div>
        <div class="headimagenes">
			<div class="pleft pimg">
				<img src="/public/img/b4c.png" alt="">
			</div>

            <div class="pright pimg">
				<img src="/public/img/b4carq.png" alt="">
			</div>
		</div>
		<div id="smalltext">
			Herramienta de productividad para la industria de TELCOS (telefonía celular).
		</div>
		<div class="programa">
			<div class="pleft">
                <p>
                    <b>Ventajas de B4C</b>
                    <br><br>
                    - Sistema WEB Parametrizable. <br>
                    - Alto desempeño. <br>
                    - Independencia del usuario para realizar cambios. <br>
                    - Alertas para detectar y corregir errores. <br>
                    - Interfaces más fáciles de usar. <br>
                    - Histórico de configuración (Para análisis de datos).
                    <br> <br>

                    <b>Descripción del Producto:</b>
                    <br> <br>
                    1) Módulo de Tasado, Facturación, Interfaces <br>
                    - El layout de los archivos de entrada es definido por el usuario. <br>
                    - La entrada pueden ser tablas de una base de datos. <br>
                    - Prediseñado para interconexión local o LD, aunque las reglas y <br>
                    operadores se configuran de manera dinámica. <br>
                    - Tiene una interfaz web en donde los usuarios de acuerdo a su roll <br>
                    pueden realizar las configuraciones de las reglas de negocio <br>
                    requeridas. No son necesarios nuevos desarrollos. <br>
                    - Proceso de carga de series de forma masiva (archivo de series). <br>
                    - Facturas para cobro y para validación. <br>
                    - Interfaces con Oracle, SAP, Archivos de texto, Web Services <br>
                </p>
            </div>

            <div class="pright">
                <img src="" alt="">
                <p>
                    2) Módulo Conciliación</br>
                    - El layout de los archivos de entrada es definido por el usuario.</br>
                    - Las reglas para conciliar son definidas por el usuario en la
                    interface WEB.</br>
                    - Procesos en segundo plano y monitoreo desde WEB.</br>
                    - Reportes detallados del proceso de conciliación.</br>
                    <br> <br>
                    3) Módulo de Monitoreo, Alertas y Reportes</br>
                    - Cuenta con pantallas predefinidas para el monitoreo de</br>
                    procesos y tendencia de tráfico.</br>
                    - El usuario puede definir sus propios reportes en la interface</br>
                    WEB. <br>
                    - Los reportes pueden ser exportados a excel.</br>
                </p>
            </div>
        </div>

        <div align="center" class="carq">
			<div class="bigtitle">Arquitectura</div><br>
			<img src="/public/img/carq.jpg" alt="">
        </div>

        <div align="center">
			<div class="bigtitle">Casos de tráfico</div><br>
			<img src="/public/img/ctrafico.png" alt="">
			<div class="bigtitle">Alta de Series y Conceptos</div><br>
			<img src="/public/img/caltas.jpg" alt="">
			<div class="bigtitle">Módulo de Facturas</div><br>
			<img src="/public/img/cfactura.jpg" alt="">
        </div>
    </div>
	<!-- FOOTER -->
	<link rel="stylesheet" href="/public/css/footer.css">
	<div class="footer">
		<div class="menus">
			<div class="contact">
				<div class="contactLogo">
					<img src="/public/img/footLogo.png">
				</div>
			</div>

			<div class="meetus">
				<div class="footerTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="footerTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="footerTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products/dpl">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
            </div>

			<div class="projects">
				<div class="footerTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>
		</div>
	</div>
</body>
</html>