<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link rel="stylesheet" href="/public/css/body.css">
	<title>Teambits</title>
</head>
<body>
	<!-- #LOGO -->
	<img src="/public/img/logo_teambits.png" class="logo">
	<!-- #NAVBAR -->
	<link rel="stylesheet" href="/public/css/navbar.css">
	<script src="/js/navbar.js"></script>
	<div class="sidenav">
		<div class="sidenavSubTitle">
			<h3>Teambits</h3>
			<h3 onclick="closeSidenav()">X</h3>
		</div>
		<div class="menus">
			<div class="meetus">
				<div class="sidenavTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="sidenavTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="sidenavTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
			</div>

			<div class="projects">
				<div class="sidenavTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="navbar">
		<!-- <div class="title">
			
			Teambits
		</div> -->
		<span class="burgerMenu" onclick="openSidenav()">Menu</span>

		<div class="links">
			<a class="link" href="/"><p>Inicio</p></a>
			<a class="link" href="/about"><p>Acerca de nosotros</p></a>
			<a class="link" href="/services"><p>Servicios</p></a>
			<a class="link" href="/products"><p>Productos</p></a>
			<a class="link" href="/projects"><p>Proyectos</p></a>
			<a class="link" href="/board"><p>Bolsa de trabajo</p></a>
		</div>
	</div>
	<!-- TEMPLATES -->
	
	<!-- FOOTER -->
	<link rel="stylesheet" href="/public/css/footer.css">
	<div class="footer">
		<div class="menus">
			<div class="contact">
				<div class="contactLogo">
					<img src="/public/img/logo_teambits.png">
				</div>
			</div>

			<div class="meetus">
				<div class="footerTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="footerTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="footerTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
			</div>

			<div class="projects">
				<div class="footerTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>
		</div>
	</div>
</body>
</html>