<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link rel="stylesheet" href="/public/css/body.css">
	<title>Teambits</title>
</head>
<body>
<!-- #LOGO -->
	<img src="/public/img/logo_teambits.png" class="logo">
<!-- #NAVBAR -->
	<link rel="stylesheet" href="/public/css/navbar.css">
	<script src="/js/navbar.js"></script>
	<div class="sidenav">
		<div class="sidenavSubTitle">
			<h3>Teambits</h3>
			<h3 onclick="closeSidenav()">X</h3>
		</div>
		<div class="menus">
			<div class="meetus">
				<div class="sidenavTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="sidenavTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="sidenavTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
			</div>

			<div class="projects">
				<div class="sidenavTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="navbar">
		<!-- <div class="title">
			
			Teambits
		</div> -->
		<span class="burgerMenu" onclick="openSidenav()">Menu</span>

		<div class="links">
			<a class="link" href="/"><p>Inicio</p></a>
			<a class="link" href="/about"><p>Acerca de nosotros</p></a>
			<a class="link" href="/services"><p>Servicios</p></a>
			<a class="link" href="/products"><p>Productos</p></a>
			<a class="link" href="/projects"><p>Proyectos</p></a>
			<a class="link" href="/board"><p>Bolsa de trabajo</p></a>
		</div>
	</div>
<!-- #TEMPLATE -->
	<link rel="stylesheet" href="/public/css/home.css">
	<div class="slider">
	</div>
	<div class="newsSection">
		<div class="newsCarousel">
			<img src="http://kesarequipments.com/images/kesar%20research.jpg" alt="">
		</div>

		<div class="news">
			<div class="title">Últimas noticias</div>
			<hr>
			<ul>
				<li>Desarrollo de aplicaciones</li>
				<li>ERP FusiónPro</li>
				<li>Nuevos Clientes</li>
				<li>Programa Outsourcing</li>
			</ul>
		</div>
	</div>

	<div class="notesSection">
		<div class="title">Notas de interés</div>
		<div class="notes">
			<div class="note">
				<img src="https://image.prntscr.com/image/c73e498d140842a2b88cedc2a221a4f7.png" alt="">
				<div class="noteTitle">ERP Fusión Pro</div>
				<div class="noteContent">
					FusiónPro es una herramienta para la planeación de recursos en todas las areas que compone una empresa...
				</div>
			</div>

			<div class="note">
				<img src="/public/img/b4c.jpeg" alt="">
				<div class="noteTitle">Programa B4C</div>
				<div class="noteContent">Entre sus principales ventajas están en ser un sistema web parametrizable de alto desempeño, independencia del usuario para realizar cambios...</div>
			</div>

			<div class="note">
				<img src="/public/img/dpl.jpeg" alt="">
				<div class="noteTitle">DPL</div>
				<div class="noteContent"></div>
			</div>
		</div>
	</div>

	<div class="referencesSection">
		<div class="title">Referencias</div>
		<div class="references">
			<div class="reference">
				<div class="refTitle">-"Gracias a Teambits, mi empresa ha crecido, reducido costos y posicioné mi marca"</div>
				<div class="refAuthor">- El cliente</div>
			</div>

			<div class="reference">
				<div class="refTitle">-"Gracias a Teambits, mi empresa ha crecido, reducido costos y posicioné mi marca"</div>
				<div class="refAuthor">- El cliente</div>
			</div>

			<div class="reference">
				<div class="refTitle">-"Gracias a Teambits, mi empresa ha crecido, reducido costos y posicioné mi marca"</div>
				<div class="refAuthor">- El cliente</div>
			</div>
		</div>
	</div>

	<div class="clientsSection" id="clients">
		<div class="title">Clientes</div>
		<div class="clients">
			<div class="client"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Nielsen_logo.svg/1200px-Nielsen_logo.svg.png" alt=""></div>
			<div class="client"><img src="https://www.izzi.mx/izzi/img/logos/izzi-black.svg" alt=""></div>
			<div class="client"><img src="https://upload.wikimedia.org/wikipedia/commons/f/f6/Alsea_logo.png" alt=""></div>
		</div>
	</div>

	<div class="contactSection">
		<div class="title">Contacto</div>
		<div class="contactForm">
			<form action="/sendmail">
				<input type="text" name="name" placeholder="Nombre">
				<input type="text" name="business" placeholder="Empresa">
				<input type="text" name="phone" placeholder="Teléfono">
				<input type="text" name="mail" placeholder="Email">
				<label for="service">Servicio: </label>
				<select name="service" placeholder="Servicio">
					<option value="training">Asesoría</option>
				</select> <br> <br>
				<input type="checkbox" name="returnCall"> <label for="returnCall">Quiero que me regresen la llamada</label> <br>
				<br>
				<input type="text" name="message" id="" placeholder="Mensaje">
				<label for="schedule">Horario de localización:</label>
				<select name="schedule">
					<option value="11am_to_2pm">11:00 am - 02:00 pm</option>
					<option value="3pm_to_8pm">03:00 pm - 08:00 pm</option>
				</select>
				<br>
				<br>
				<input type="submit" value="Enviar">
			</form>
			<div id="contactMap"></div>
		</div>
		<br>

		<div class="customerService">
			<div class="title">Atención a cliente</div>
			<div class="content">
				<p>
					De Lunes a Viernes /De Lunes a Domingo <br>
					Calle Montecito No. Exterior 11 No. Interior Pent House 4 Colonia Nápoles <br>
					Municipio Benito Juárez Estado Ciudad de México México CP.03810 <br>
					<br>
					Ing.Javier Rodríguez Morales <br>
					Comercialización <br>
					javier.rodriguez@teambits.com.mx <br>
					Tel 01 55 5523 9501
					<br><br>
					Alfredo Torres <br>
					alfredo.torres@teambits.mx <br><br>

				</p>
			</div>
		</div>
	</div>
	<!-- FOOTER -->
	<link rel="stylesheet" href="/public/css/footer.css">
	<div class="footer">
		<div class="menus">
			<div class="contact">
				<div class="contactLogo">
					<img src="/public/img/logo_teambits.png">
				</div>
			</div>

			<div class="meetus">
				<div class="footerTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="footerTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="footerTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
			</div>

			<div class="projects">
				<div class="footerTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>
		</div>
	</div>
	<!-- #MAIN -->
	<script>
		var map
		function initMap() {
			map = new google.maps.Map(document.getElementById("contactMap"), {
				center: { lat: 19.3950001, lng: -99.1737762 },
				zoom: 15
			})
		}
	</script>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAmaCOIkyNT6IkZXnZMsLer6dKjrt9EtdE&callback=initMap" async defer></script>
</body>
</html>