<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link rel="stylesheet" href="/public/css/body.css">
	<title>Teambits</title>
</head>
<body>
	<!-- #LOGO -->
	<img src="/public/img/logo_teambits.png" class="logo">
	<!-- #NAVBAR -->
	<link rel="stylesheet" href="/public/css/navbar.css">
	<script src="/js/navbar.js"></script>
	<div class="sidenav">
		<div class="sidenavSubTitle">
			<h3>Teambits</h3>
			<h3 onclick="closeSidenav()">X</h3>
		</div>
		<div class="menus">
			<div class="meetus">
				<div class="sidenavTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="sidenavTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="sidenavTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
			</div>

			<div class="projects">
				<div class="sidenavTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="navbar">
		<!-- <div class="title">
			
			Teambits
		</div> -->
		<span class="burgerMenu" onclick="openSidenav()">Menu</span>

		<div class="links">
			<a class="link" href="/"><p>Inicio</p></a>
			<a class="link" href="/about"><p>Acerca de nosotros</p></a>
			<a class="link" href="/services"><p>Servicios</p></a>
			<a class="link" href="/products"><p>Productos</p></a>
			<a class="link" href="/projects"><p>Proyectos</p></a>
			<a class="link" href="/board"><p>Bolsa de trabajo</p></a>
		</div>
	</div>
	<!-- TEMPLATES -->
	<link rel="stylesheet" href="/public/css/projects.css">
	<div class="sectionTitle" align="center">Proyectos destacados</div>
	<div class="section">
		<div class="project">
			<div class="projectTitle">Sistema de auditoría para agencias de automóviles</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para PWC</b> <br>
				<b>Descripción:</b> Teambits, S.C desarrolló la aplicación para dispositivos móviles, con los requerimientos
				de PWC, para auditara las agencias de automóviles Nissan, en tiempo real y con evidencias incluidas (fotografías).
				Con ello, logra evaluar y recaba la informción de cada agencia a nivel República Mexicana y Centro América. <br>
				<b>Ventajas: </b> La información en tiempo real permite la toma de decisiones para el logro de objetivos de manera
				oportuna, y con ello, elaborar planes de recuperación y detectar nuevas oportunidades de negocio (nuevas agencias,
				nuevos territorios, nuevos nichos). Próximamente otras marcas de automóviles, clientes de PWC, estarán usando
				la aplicación. <br>
				<b>Tecnologías: </b> La tecnología utilizada es .Net, con desarrollo para dispositivos móviles iPad.
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">Desarrollo y mantenimiento de sistemas para evaluaciones psicométricas y cognoscitivas</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para ARMSTRONG</b> <br>
				<b>Descripción:</b> Teambits, S.C trabajó en conjunto con Amstrong en el desarrollo de aplicaciones para ser
				accesadas vía internet y en dispositivos móviles para evaluar a personal, incluyendo pruebas en habilidades técnicas,
				pruebas psicométricas y pruebas de control de confianza para aplicarlas y evaluarlas en tiempo real. <br>
				<b>Ventajas: </b> Aplicación que en la actualidad es ocupada por el gobierno y por empresas del sector privado
				<br>
				<b>Tecnologías: </b> La tecnología utilizada es .Net y aplicativo para dispositivos móviles Android.
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">
				Actualización de sistemas fiscales para Costa Rica, Honduras, Colombia, Perú y República Dominicana
			</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para ADAM (ATI/ROW)</b> <br>
				<b>Descripción:</b> A solicitud de ADAM (empresa americana dedicada a dar servicios de administración de capital
				humano) se realizó la adecuación de aplicativos fiscales y de nómina para cumplir con las nuevas leyes fiscales
				2017 y en concordancia a las leyes de cada país. <br>
				<b>Ventajas: </b> Proporciona información que cumple con los lineamientos fiscales, en tiempo y forma. Para ello,
				se aplicaron pruebas unitarias y de conjunto en diferentes ambientes y diferentes reglas de negocio. <br>
				<b>Tecnologías: </b> La tecnología utilizada es .Net
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">
				Sistema de reconocimiento biométrico (Huellas digitales y reconocimiento facial)
			</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para ATC - Alta Tecnología en Computación</b> <br>
				<b>Descripción:</b> Se desarrolló un sistema que permite enrolar a personas que demás de registrar en el sistema
				información general. Permite guardar la información biométrica de las huellas dactilares y del rostro, así como
				la digitalización de documentos como el INE, pasaporte y otros documentos. <br>
				<b>Ventajas: </b> Este aplicativo permite mejorar la seguridad contra el robo de identidad y fraudes, por ejemplo
				en instituciones bancarias, instituciones gubernamentales, etc. <br>
				<b>Tecnologías: </b> Lectores biométricos de huellas, cámaras para la captura de rostro, generar plantillas binarias
				que contienen la información de la biométrica capturada, .Net, comparación 1 a 1 y 1 a N para la comparación
				biométrica.
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">
				Sistema de administración y control de numeración de telefonía
			</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para TotalPlay</b> <br>
				<b>Descripción:</b> Este sistema permite administrar los rangos de numeración que asigna la IFT a las compañías
				telefónicas, administrar los números que son asignados a los diferentes planes tarifarios de los clientes, así
				como la administración de la portabilidad numérica. <br>
				<b>Ventajas: </b> A parte de la administración, se mejora el aprovisionamientode rangos de numeración de los
				switches, considerando también los números que se portan entre compañias telefónicas. <br>
				<b>Tecnologías: </b> Desarrollado en Java, protocolo MML para aprovisionamiento a los elementos de red, y base
				de datos Oracle.
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">
				Sistema de administración de imágenes del Acervo Histórico de FICA
			</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para FICA</b> <br>
				<b>Descripción:</b> Fundación FICA contiene un Acervo de libros, fotografías y videos de las diferentes construcciones
				de México, las cuales son promovidas en su página web. <br>
				<b>Ventajas: </b> Poder mostrar y/o distribuir las fotografías, videos, libros del acervo histórico, compradas
				por los clientes. <br>
				<b>Tecnologías: </b> PHP, Html5, Base de datos SQL Server.
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">
				Implementación de módulos de ERP de pago de comisiones en México y Perú
			</div>
			<p class="projectContent">
				<b>Proyecto desarrollado por Virgin Movil</b> <br>
				<b>Descripción:</b> Implementar del sistema FusionPro los módulos de inventarios y punto de venta web y móvil,
				así como personalizar el cálculo de comisiones de acuerdo a las reglas de negocio. <br>
				<b>Ventajas: </b> El licenciamiento de FusionProse realizó en la modalidad de SAS donde se ofrece soporte, monitoreo,
				DRP, y en la cual podemos configurar el sistema de acuerdo a las necesidades del negocio.<br>
				<b>Tecnologías: </b> .Net, SQL Server, Android, hiperconvergencia.
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">
				Aplicación Móvil: Mi ATT
			</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para AT&T</b> <br>
				<b>Descripción:</b> Aplicativo Móvil en que los clientes de AT&T pueden consultar su estado de consumos de acuerdo
				a su plan tarifario. Este proyecto se realizó para iOS. <br>
				<b>Ventajas: </b> Reducción de incidentes y/o consultas realizadas por al cliente al área de Call Center de AT&T.<br>
				<b>Tecnologías: </b> iOS, PL/SQL, WebServices, SOA
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">
				Aplicación Móvil: Mi Iusacell
			</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para AT&T</b> <br>
				<b>Descripción:</b> Aplicativo Móvil en el que el cliente de Iusacell consulta el estado de sus consumos de acuerdo
				a su plan tarifario. Este proyecto se realizó para iOS y Android. <br>
				<b>Ventajas: </b> Reducción de incidentes y/o consultas realizadas por al cliente al área de Call Center de Iusacell<br>
				<b>Tecnologías: </b> .OS, PL/SQL, WebServices, SOA.
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">
				Sistema Móvil para el Enrolamiento de Clientes y Seguimiento a Cobranza
			</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para Alcance Financiera</b> <br>
				<b>Descripción:</b> Aplicativo móvil que permite dar seguimiento a sus ejecutivos, realizar altas, bajas y cambios
				de usuarios, para la administración de la cobranza de sus clientes, permitiendo el seguimiento, control y denición
				de rutas de visitas a clientes por medio de google maps, así como llevar la agenda de atención. <br>
				<b>Ventajas: </b> Este aplicativo móvil Android se desarrolló para tener una planeación de las mejores rutas
				de visitas a clientes, mostrando la ruta en el Google Maps, así como controlar la administración de territorios
				de ejecutivos de venta.
				<br>
				<b>Tecnologías: </b> .Google Maps, WebServices, SQL Server, Android, SOA.
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">
				Sistema Web de Monitoreo de Traco de Redes
			</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para Bestel</b> <br>
				<b>Descripción:</b> Implementar un sistema que permita la conguración, administración, integración, desarrollo,
				soporte y mantenimiento de la totalidad de los servicios ofrecidos en el portal único de Gestión <br>
				<b>Ventajas: </b> Ofrecer a sus clientes de forma oportuna el estatus de sus equipos al contar con un portal
				único para la administración y monitoreo de los sistemas en los diferentes clientes, logrando que se integren
				a través de las secciones del mismo aplicativo. <br>
				<b>Tecnologías: </b> Java, Spring Faces, WebServices, SOA, PL/SQL.
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">
				Desarrollo sistema OTA para Telefónica Móviles
			</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para ...</b> <br>
				<b>Descripción:</b> Desarrollo de sistema empresarial para cambio de simcard mediante OTA utilizando arquitectura
				MVC en servidor BEA WebLogic. <br>
				<b>Ventajas: </b> Con este proyecto se logró disminuir el manejo de almacenes especícos por región. Mediante
				laactivación de OTA se activa simmcard en línea. <br>
				<b>Tecnologías: </b> Struts MVC, WebLogic.
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">
				Reingeniería del sistema de mediación GPRS sustituyendo a sistema BMP Telefónica Móviles
			</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para ...</b> <br>
				<b>Descripción:</b> Desarrollo de sistema mediación específico para el procesamiento de tráfico de datos GPRS sustituyendo
				el flujo del sistema BMP Ericksson. <br>
				<b>Ventajas: </b> ... <br>
				<b>Tecnologías: </b> Ansi C, ProC, Shells Unix
			</p>
		</div>

		<div class="project">
			<div class="projectTitle">
				Desarrollo Web Scheduler Empresarial Web para Iusacell
			</div>
			<p class="projectContent">
				<b>Proyecto desarrollado para Iusacell</b> <br>
				<b>Descripción:</b> Migración de sistema calendarización de tareas, se migro la arquitectura que utilizaba componente
				EJB Timer hacia framework Quartz para soportar clustering. Optimización de procesos de carga con Shell´s y Proc
				para detalle de llamadas. Plataforma Rational IBM. <br>
				<b>Ventajas: </b> En la versión original del proyecto al instalar el componente en un cluster de servidores web,
				el timer se disparaba varias veces. Esto se logró mitigar utilizando el framework Quartz enterprise con ello
				fue posible la instalación del proyecto Web en un cluster y que las actividades se disparan en secuencia y orden
				<br>
				<b>Tecnologías: </b> Quartz, J2EE Web, Plataforma Rational IBM, C, Proc, Shells Unix
			</p>
		</div>
	</div>
	<!-- FOOTER -->
	<link rel="stylesheet" href="/public/css/footer.css">
	<div class="footer">
		<div class="menus">
			<div class="contact">
				<div class="contactLogo">
					<img src="/public/img/logo_teambits.png">
				</div>
			</div>

			<div class="meetus">
				<div class="footerTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="footerTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="footerTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
			</div>

			<div class="projects">
				<div class="footerTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>
		</div>
	</div>
</body>
</html>