<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="/public/css/training.css">
	<link rel="stylesheet" href="/public/css/body.css">
	<title>Teambits</title>
</head>
<body>
	<!-- #LOGO -->
	<img src="/public/img/logo_teambits.png" class="logo">
	<!-- #NAVBAR -->
	<link rel="stylesheet" href="/public/css/navbar.css">
	<script src="/public/js/navbar.js"></script>
	<div class="sidenav">
		<div class="sidenavSubTitle">
			<h3>Teambits</h3>
			<h3 onclick="closeSidenav()">X</h3>
		</div>
		<div class="menus">
			<div class="meetus">
				<div class="sidenavTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="sidenavTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="sidenavTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
			</div>

			<div class="projects">
				<div class="sidenavTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="navbar">
		<!-- <div class="title">
			
			Teambits
		</div> -->
		<span class="burgerMenu" onclick="openSidenav()">Menu</span>

		<div class="links">
			<a class="link" href="/"><p>Inicio</p></a>
			<a class="link" href="/about"><p>Acerca de nosotros</p></a>
			<a class="link" href="/services"><p>Servicios</p></a>
			<a class="link" href="/products"><p>Productos</p></a>
			<a class="link" href="/projects"><p>Proyectos</p></a>
			<a class="link" href="/board"><p>Bolsa de trabajo</p></a>
		</div>
	</div>
    <div id="training">
        <div class="ttitle">
			Capacitación en Tecnologías de la Información 
        </div>
        <p>
            Ofrecemos el mejor grupo de consultores, dedicados a la investigación e implementación de nuevas tecnologías en diversas plataformas, lenguajes,
            herramientas, y base de datos.
            Cursos y planes de capacitación y cursos de preparación para certificación de evaluaciones oficiales, como:
        </p>
        <div class="tcap">
            <div class="content">
                <ul>
                    <li>UNIX (Sun Solaris, HP-UX, Digital, Unix, Tr64, AIX)</li>
                    <li>Windows (95, 98, NT, 2000, XP, Vista, .Net) (se necesita actualizar?)</li>
                    <li>Lenguajes de programación estructurada y orientada a objetos:</li>
                    <li>Java, C/C++, Pro*C. Pl Shell, Visual Basic, Framework .Net, Mobile.</li>
                    <li>SAP, Manejadores de Bases de datos:</li>
                    <li>Oracle, SQL Server, MySQL, PostgreSQL, DB2, Sybase, entre otros.</li>
                </ul>
            </div>
            <div class="image">
                <img src="/public/img/imgtrain.png">
            </div>
        </div>

        <div class="tcur" align="center">
			<div class="subtitle">Brindamos capacitación en: </div>
			<div class="tcurContent">
				<div class="pleft">
					<div class="type">
						<b>Manejadores de base de datos</b>
						<br>
						<br>
						Cursos para el desarrollo de bases de datos, desde creación de tablas hasta tining y creación
						de Triggers, PL, entre otros.
					</div>
					<br>
					<div class="type">
						<b>Seminarios de Planeación</b>
						<ul>
							<li>-Evaluación de Proyectos de Inversión </li>
							<li>-Administración de Proyectos en Telecomunicaciones </li>
							<li>-Re-ingeniería de Procesos en las Telecomunicaciones</li>
						</ul>
				
					</div>
				
					<div class="type">
						<b>Metodología SCRUM de ITIL</b>
						<br><br>
						-Adoptar una estrategia de desarrollo incremental 
						<br>
						-Basar la calidad del resultado más en el conocimiento
						táctico de las personas 
						<br>
						-Solapamiento de las diferentes fases del desarrollo
					</div>
				</div>
					
				<div class="pright">
					<div class="type">
						<b>Cursos personalizados</b>
						<br> <br>
						También contamos con una coleccion de cursos para satisfacer las necesidades tecnológicas de proyectos
						que requieren temas especificos de conocimiento
					</div>
					<br>
					<div class="type">
						<b>Sistemas Ofimáticas y de su uso general</b>
						<br> <br>
						Cursos de capacitación para personal de oficina que busca mejorar el uso de los recursos
						informáticos en su actividad cotidiana
					</div>
					<br>
					<div class="type">
						<b>Lenguajes de desarrollo</b>
						<br> <br>
						Cursos esarrollados bajo estándares de enseñanza probados que facilitan el proceso de aprendizaje y entretenimiento
					</div>
				</div>
			</div>
        </div>
    </div>
    <link rel="stylesheet" href="/public/css/footer.css">
	<div class="footer">
		<div class="menus">
			<div class="contact">
				<div class="contactLogo">
					<img src="/public/img/footLogo.png">
				</div>
			</div>

			<div class="meetus">
				<div class="footerTitle">Conócenos</div>
				<ul class="urls">
					<li><a href="/about">¿Quienes somos?</a></li>
					<li><a href="/about#alliances">Alianzas</a></li>
					<li><a href="/about#valuesSection">Nuestros valores</a></li>
					<li><a href="/#clients">¿Quienes son nuestros clientes?</a></li>
				</ul>
			</div>

			<div class="services">
				<div class="footerTitle">Servicios</div>
				<ul class="urls">
					<li><a href="/services/outsourcing">Outsourcing</a></li>
					<li><a href="/services/training">Capacitación</a></li>
					<li><a href="/services/development">Desarrollo de software</a></li>
				</ul>
			</div>

			<div class="products">
				<div class="footerTitle">Productos</div>
				<ul class="urls">
					<li><a href="/products/b4c">B4C</a></li>
					<li><a href="/products/dpl">DPL</a></li>
					<li><a href="/products/erp">ERP FusionPro</a></li>
				</ul>
			</div>

			<div class="projects">
				<div class="footerTitle">Proyectos</div>
				<ul class="urls">
					<li><a href="/projects">Proyectos destacados</a></li>
				</ul>
			</div>
		</div>
	</div>
</body>
</html>